# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Back
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
